// Auto-generated file - do not edit manually
// This file is generated by error-extractor.ts
// Run: npm run extract:errors

export const ERROR_MAP: Record<
  string,
  Record<number, { constantName: string; errorMessage: string }>
> = {
  identity: {
    '0': {
      constantName: 'EWrongVersion',
      errorMessage:
        'Identity module version does not match the package version',
    },
    '1': {
      constantName: 'EModuleMissing',
      errorMessage: 'Identity module is not installed on this entity',
    },
  },
  entity: {
    '0': {
      constantName: 'EWrongVersion',
      errorMessage: 'Entity version does not match the package version',
    },
    '1': {
      constantName: 'ENotLocked',
      errorMessage: 'Entity is not locked',
    },
    '2': {
      constantName: 'EWrongEntity',
      errorMessage: 'Module does not belong to this entity',
    },
    '3': {
      constantName: 'ERequirementNotModuleScoped',
      errorMessage: 'Requirement is not module-scoped',
    },
    '4': {
      constantName: 'EUnknownAction',
      errorMessage: 'Action is not enabled on this entity',
    },
    '5': {
      constantName: 'EModuleExists',
      errorMessage: 'Module is already installed',
    },
    '6': {
      constantName: 'EModuleMissing',
      errorMessage: 'Module is not installed',
    },
    '7': {
      constantName: 'EActionExists',
      errorMessage: 'Action is already enabled',
    },
    '8': {
      constantName: 'EEntityAlreadyExists',
      errorMessage: 'Entity already exists for this key',
    },
  },
  entity_key: {
    '0': {
      constantName: 'EIdEmpty',
      errorMessage: 'Entity ID must be non-zero',
    },
    '1': {
      constantName: 'ETenantEmpty',
      errorMessage: 'Tenant must be non-empty',
    },
  },
  request: {
    '0': {
      constantName: 'EWrongRequirementType',
      errorMessage: 'Next requirement does not match the expected type',
    },
    '1': {
      constantName: 'EFrameNotEmpty',
      errorMessage: 'Frame still holds an unconsumed requirement',
    },
    '2': {
      constantName: 'ERequestNotComplete',
      errorMessage: 'Request has unsatisfied requirements',
    },
    '3': {
      constantName: 'ENoRequirements',
      errorMessage: 'Request has no requirements to take',
    },
  },
  admin_service: {
    '0': {
      constantName: 'EUnauthorizedAdmin',
      errorMessage: 'Sender is not an admin',
    },
    '1': {
      constantName: 'EUnauthorizedSponsor',
      errorMessage: 'Sender is not a sponsor',
    },
  },
  location_service: {
    '0': {
      constantName: 'EProximityMismatch',
      errorMessage: 'Location proof does not match the required proximity',
    },
  },
  owner_cap: {
    '0': {
      constantName: 'ENotOwner',
      errorMessage: 'Cap does not grant access to this entity',
    },
    '1': {
      constantName: 'ENotTransferable',
      errorMessage: 'Access cap is soulbound and cannot be transferred',
    },
    '2': {
      constantName: 'EWrongVersion',
      errorMessage: 'Cap version does not match the package version',
    },
  },
}

/**
 * Whether the given module is one of our contracts (vs a framework/external module)
 */
export function isKnownModule(moduleName: string): boolean {
  return moduleName in ERROR_MAP
}

/**
 * Gets the error constant name for a given module and error code
 */
export function getErrorConstantName(
  moduleName: string,
  errorCode: number,
): string | undefined {
  return ERROR_MAP[moduleName]?.[errorCode]?.constantName
}

/**
 * Gets the error message for a given module and error code
 */
export function getErrorMessage(
  moduleName: string,
  errorCode: number,
): string | undefined {
  return ERROR_MAP[moduleName]?.[errorCode]?.errorMessage
}

/**
 * Gets both the error constant name and message for a given module and error code
 */
export function getErrorInfo(
  moduleName: string,
  errorCode: number,
): { constantName: string; errorMessage: string } | undefined {
  return ERROR_MAP[moduleName]?.[errorCode]
}
