// Loads the error map generated by error-extractor.ts (error-map.json).
// The data is fetched once at startup; lookups below stay synchronous.

type ErrorMap = Record<
  string,
  Record<number, { constantName: string; errorMessage: string }>
>

const response = await fetch('error-map.json')
const ERROR_MAP = (await response.json()) as ErrorMap

export function isKnownModule(moduleName: string): boolean {
  return moduleName in ERROR_MAP
}

export function getErrorConstantName(
  moduleName: string,
  errorCode: number,
): string | undefined {
  return ERROR_MAP[moduleName]?.[errorCode]?.constantName
}

export function getErrorMessage(
  moduleName: string,
  errorCode: number,
): string | undefined {
  return ERROR_MAP[moduleName]?.[errorCode]?.errorMessage
}

export function getErrorInfo(
  moduleName: string,
  errorCode: number,
): { constantName: string; errorMessage: string } | undefined {
  return ERROR_MAP[moduleName]?.[errorCode]
}
