// Loads the error map generated by error-extractor.ts (error-map.json).
// The data is fetched once at startup; lookups below stay synchronous.

type ErrorMap = Record<
  string,
  Record<number, { constantName: string; errorMessage: string }>
>

async function loadErrorMap(): Promise<ErrorMap> {
  try {
    const response = await fetch('error-map.json')
    if (!response.ok) {
      throw new Error(`HTTP ${response.status}`)
    }
    return (await response.json()) as ErrorMap
  } catch (error) {
    console.error('Failed to load error-map.json, using empty map:', error)
    return {}
  }
}

const ERROR_MAP = await loadErrorMap()

export function isKnownModule(moduleName: string): boolean {
  return Object.hasOwn(ERROR_MAP, moduleName)
}

export function getErrorConstantName(
  moduleName: string,
  errorCode: number,
): string | undefined {
  return ERROR_MAP[moduleName]?.[errorCode]?.constantName
}

export function getErrorMessage(
  moduleName: string,
  errorCode: number,
): string | undefined {
  return ERROR_MAP[moduleName]?.[errorCode]?.errorMessage
}

export function getErrorInfo(
  moduleName: string,
  errorCode: number,
): { constantName: string; errorMessage: string } | undefined {
  return ERROR_MAP[moduleName]?.[errorCode]
}
